dbt_databricks_usecase:
  
  target: mysql

  outputs:
    databricks:
      type: databricks
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      schema: "{{ env_var('DATABRICKS_SCHEMA') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
    
    mysql:
      type: mysql
      server: "{{ env_var('MYSQL_HOST') }}"
      port: 3306
      user: "{{ env_var('MYSQL_USER') }}"
      password: "{{ env_var('MYSQL_PASSWORD') }}"
      schema: "{{ env_var('MYSQL_SCHEMA') }}"
      database: "{{ env_var('MYSQL_DATABASE') }}"
      threads: 1
